
FROM node:slim AS build-stage
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run lint:html
RUN npm run lint:jsfix
RUN npm run lint:js
RUN npm run test


FROM nginx:alpine
COPY --from=build-stage /app /usr/share/nginx/html
EXPOSE 80